version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dallas_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order:
    build:
      context: ../
      dockerfile: services/order/Dockerfile
    environment:
      - DATABASE_URL=postgres://dev:dev@postgres:5432/dallas_dev
      - PORT=3001
    depends_on:
      - postgres
    ports:
      - '3001:3001'

volumes:
  postgres_data: