apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  namespace: default
  labels:
    app: order
stringData:
  DATABASE_URL: "postgres://user:strongpassword@postgres:5432/dallas"
  JWT_SECRET: "your-very-strong-secret"
  API_KEY: "your-api-key"
